apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
spec:
  metrics:
    - name: success-rate
      successCondition: result[0] > 0.95
      failureCondition: result[0] < 0.90
      provider:
        prometheus:
          address: http://prometheus:9090
          query: |
            sum(rate(http_requests_total{status!~"5..",version="v2"}[1m]))
            /
            sum(rate(http_requests_total[1m]))